services:
  - type: web
    name: song-note-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: '22'
      - key: DATABASE_URL
        fromDatabase:
          name: song-note-database
          property: connectionString

databases:
  - name: song-note-database
    plan: free
    region: singapore
    version: 18
